### ISSUE TITLE
CTAM Test Full Device Update [F1] Testcase

### ISSUE THREAD

**Issue by khaderbmc** [opencomputeproject/ocp-diag-ctam#33]
Hi @MeritedHobbit ,

Unable to run the "F1" test case.

I have a "BKC_XX.pldm" pldm bundle image to flash and ran the "CTAM Test Full Device Update [F1] Testcase" and also updated the "package_info.json"  with path and package(pldm file).

{
  "GPU_FW_IMAGE": {
      "Path": "directopry from where we need to take the file.",
      "Package": "BKC_XX.pldm",
      "Version": "version",
      "JSON": "<fwpkg_json_file.json>",
      "Vendor": "Vendor Name"
    }
}

what should be the contents in the "<fwpkg_json_file.json>"  ?

Regards,
Khader

**Comment by MeritedHobbit** [comment]
Hi @khaderbmc ,

We have two options. Either get the header information from the gpu supplier as a json file. Or you could generate the header.json file from this repo. https://github.com/microsoft/pldm-fw-pkgr/tree/main (assuming you are using pldmspec 1.0)

**Comment by khaderbmc** [comment]
Thanks for the quick help @MeritedHobbit

**Comment by khaderbmc** [comment]
Hi @MeritedHobbit ,

I have provided the "Package": "BKC_XX.pldm" as pldm bundle in the  "package_info.json"  . 


{
"GPU_FW_IMAGE": {
"Path": "directopry from where we need to take the file.",
"Package": "BKC_XX.pldm",
"Version": "version",
"JSON": "<fwpkg_json_file.json>",
"Vendor": "Vendor Name"
}

Will the F1 testcase be able to update the FW using pldm bundle or the package  should be the bin file ?
